#!/bin/bash

##
## Start local X11 server
##

#
# Requires VcXsrv from https://sourceforge.net/projects/vcxsrv/
#
# $ ln -s `pwd`/wsl-startx ~/bin/startx
# $ startx
#

export DISPLAY=:0
VCXSRV="/mnt/c/Program Files/VcXsrv/vcxsrv.exe"
ARGS="-multiwindow -clipboard -wgl $DISPLAY"

LOG=~/.vcxsrv.log
XINITRC=~/.xinitrc

# Make sure VcXsrv is installed
if [ ! -f "$VCXSRV" ]; then
	echo "Could not find X11 server from '$VCXSRV'" >&2
	exit 1
fi

# Launch the X11 server
nohup "$VCXSRV" $ARGS "$@" >$LOG 2>&1 &

# Launch optional X11 clients
if [ -f "$XINITRC" ]; then
	while ! grep -q "successfully opened the display" $LOG; do sleep 0.2; done
	nohup /bin/sh $XINITRC >>$LOG 2>&1 &
fi

