#!/bin/sh

##
## Open a file or directory from WSL to graphical Windows
##

#
# Symlink this to ~/bin/open and ~/bin/xdg-open
#
# $ ln -s `pwd`/wsl-open ~/bin/open
# $ ln -s `pwd`/wsl-open ~/bin/xdg-open
#
# $ open /usr/share/pixmaps/debian-logo.png
# $ xdg-open ~
#

CMD="/mnt/c/Windows/system32/cmd.exe"
EXPLORER="/mnt/c/Windows/explorer.exe"

ARG="$1"

# Check argument
if [ ! "$ARG" ]; then
	echo "Usage: `basename $0` <file or directory>" >&2
	exit 1

# Handle URLs
elif echo "$ARG" | egrep -q "^https?://"; then
	exec $CMD /C "start $ARG" 2>/dev/null &

# Check file/directory existence
elif [ ! -e "$ARG" ]; then
	echo "Error: File or directory '$ARG' not found!" >&2
	exit 1

# Handle directories
elif [ -d "$ARG" ]; then
	cd "$ARG" && exec $EXPLORER . 2>/dev/null &

# Handle files
else
	DIR="`dirname \"$ARG\"`"
	EXE="`basename \"$ARG\"`"
	UNC="`wslpath -w \"$DIR\" | tr '\\134' '\\134\\134\\134\\134'`"

	exec $CMD /C pushd "$UNC" \&\& ".\\$EXE" 2>/dev/null &
fi
