#!/bin/sh

##
## Open a file or directory from WSL to graphical Windows
##

#
# Symlink this to ~/bin or /usr/local/bin using symlink
# names 'open' (from macOS) and 'xdg-open' (Linux standard)
#
# $ ln -s wsl-open ~/bin/open/open
# $ ln -s wsl-open ~/bin/open/xdg-open
# $ open /usr/share/pixmaps/debian-logo.png
# $ xdg-open ~
#

ARG="$1"

# Check argument
if [ ! "$ARG" ]; then
	echo "Usage: `basename $0` <file or directory>" >&2
	exit 1

# Check file/directory existence
elif [ ! -e "$ARG" ]; then
	echo "Error: File or directory '$ARG' not found!" >&2
	exit 1

# Handle directories
elif [ -d "$ARG" ]; then
	cd "$ARG" && exec explorer.exe . 2>/dev/null &

# Handle files
else
	exec cmd.exe /C "`wslpath -m \"$ARG\"`" 2>/dev/null &
fi

